more off;
fk = 10.^linspace(-4,-1,31);
[om_m,om_v,om_bh2,h,an,sigma8] = cdenCosparamInit;
ips = 3;
Tk_file = 'tkO3111L6889h6766N2242_eh_PLANCK18.dat';
nrows = 650;
% Convert to strings
som_m = num2str(om_m,'%.1f');
som_v = num2str(om_v,'%.1f');
som_bh2 = num2str(om_bh2,'%.1f');
sh = num2str(h,'%.1f');
san = num2str(an,'%.1f');
ssigma8 = num2str(sigma8,'%.1f');
sips = num2str(ips,'%i');
suffix = '_omm_';
suffix = strcat(suffix,som_m);
suffix = strcat(suffix,'_omv_');
suffix = strcat(suffix,som_v);
suffix = strcat(suffix,'_ombh2_');
suffix = strcat(suffix,som_bh2);
suffix = strcat(suffix,'_h_');
suffix = strcat(suffix,sh);
suffix = strcat(suffix,'_an_');
suffix = strcat(suffix,san);
suffix = strcat(suffix,'_s8_');
suffix = strcat(suffix,ssigma8);
suffix = strcat(suffix,'_ips_');
suffix = strcat(suffix,sips);
prefix = 'cdenPowsp';
outfile = strcat(prefix,suffix);
matoutfile = strcat(outfile,'.mat');
outfile = strcat(outfile,'.out');
[pnorm,Gamma,Tk] = cdenPowspInitFile(om_m,om_v,om_bh2,h,an,sigma8, ...
                                     ips,Tk_file,nrows);
PS = cdenPowsp(fk,pnorm,Gamma,an,Tk,ips);
lenfk = length(fk);
Aout = [fk(:),PS(:)];
fido = fopen(outfile,'w');
fprintf(fido,'%8.6f %16.6e\n',Aout');
fclose(fido);
save(matoutfile, 'fk', 'PS', 'om_m', 'om_v','om_bh2', 'h', 'an', 'sigma8', 'ips','Tk_file');
